######################################################################
# Automatically generated by qmake (3.0) Tue Apr 28 16:46:11 2015
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += .
QT += widgets
QT += network
# Input
HEADERS += client.h
SOURCES += client.cpp client_main.cpp
