######################################################################
# Automatically generated by qmake (3.0) Tue Apr 28 16:46:23 2015
######################################################################

TEMPLATE = app
TARGET = server
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets 
QT += network

# Input
HEADERS += server.h SSLServer.h
SOURCES += server.cpp server_main.cpp SSLServer.cpp
